### ISSUE TITLE
Implement aggregate

### ISSUE THREAD

**Issue by shntnu** [cytomining/cytotools#1]

**Comment by cells2numbers** [comment]
the aggregate implementation in cytominer_scripts has only tow input variables, one sql file and one output file, and it aggregates always per well. Is the goal to implement a more flexible version?

**Comment by cells2numbers** [comment]
@shntnu  aggregate is splitted in the R function aggregate.R and a script to make it accessible from CLI. Any naming conventions for the script part? I would go for cy_aggregate or cyaggregate

**Comment by shntnu** [comment]
#2
