### ISSUE TITLE
Implement clean

### ISSUE THREAD

**Issue by shntnu** [cytomining/cytotools#19]
This is intended to be used right after the SQLite file is produced. It strips `Image_` from column names with prefix `Image_Metadata_` in the `image` table.

I'm not thrilled about the fact that this is a hack, but it helps remove code downstream where this is done repeatedly

Here's a stub

    db <- DBI::dbConnect(RSQLite::SQLite(), sqlite_file)
    
    image <- dplyr::tbl(src = db, "image") %>%
    
    columns_names <- colnames(image) %>% stringr::str_sub("^Image_Metadata_")
    
    purrr::walk(columns_names, function(column_name) DBI::dbSendQuery(db, sprintf("'UPDATE image SET %s = %s;'", column_name, stringr::str_replace(column_name, "^Image_", ""))))
    
    DBI::dbDisconnect(db)

**Comment by shntnu** [comment]
We had discussed this here https://github.com/cytomining/cytotools/pull/12#discussion_r156239872

**Comment by shntnu** [comment]
Alternatively, we can consider changing it in `cytominer-database`. The `Image_` prefix happens here: https://github.com/cytomining/cytominer-database/blob/f66d688a8a77ef9411dd8a646f8e86c9b366d509/cytominer_database/ingest.py#L83

**Comment by shntnu** [comment]
@mcquin What do you think of doing it like this: https://github.com/cytomining/cytominer-database/pull/87

**Comment by mcquin** [comment]
Resolved https://github.com/cytomining/cytominer-database/pull/87
