### ISSUE TITLE
Don't include aggregation tag

### ISSUE THREAD

**Issue by shntnu** [cytomining/cytotools#23]
Update these files to be consistent with new behavior of `cytominer::aggregate`

https://github.com/cytomining/cytotools/blob/master/inst/extdata/backend/batch0/SQ00015116/SQ00015116_augmented.csv
https://github.com/cytomining/cytotools/blob/master/inst/extdata/backend/batch0/SQ00015116/SQ00015116.csv
https://github.com/cytomining/cytotools/blob/master/tests/testthat/test-aggregate.R

See https://github.com/cytomining/cytominer/pull/121

**Comment by mcquin** [comment]
Let's resolve this as part of #22, since that PR already includes changes to those files.
